### ISSUE TITLE
Install and practic OpenStack

### ISSUE THREAD

**Issue by bjhuangr** [mfcloud/kolla-ansible#11]

**Comment by haolp** [comment]
Successfully tried and installed devstack, created a test vm via devstack.

**Comment by haolp** [comment]
Successfully tried and installed openstack via kolla-ansible on x86 host.

**Comment by haolp** [comment]
Successfully deploy OpenStackCE on x86 as controller and s390vm as compute node.

**Comment by bjhuangr** [comment]
Good.
