### ISSUE TITLE
Tests of OpenStackCE for kvm on linuxone

### ISSUE THREAD

**Issue by dongyanyang** [mfcloud/kolla-ansible#14]
Including document test, deploy process test, openstack functions test, eg. VXLAN of openvswitch.

**Comment by dongyanyang** [comment]
Tested the openstack functions by myself.

Recorded steps to deploy VM on s390x kvm:
https://ibm.ent.box.com/notes/336222590135

**Comment by haolp** [comment]
Completed the test of openstack functions, can deploy a VM with floating IP associated.
