### ISSUE TITLE
Investigate the openstack dashboard logon url/port issue within kolla-ansible deployed cloud

### ISSUE THREAD

**Issue by dongyanyang** [mfcloud/kolla-ansible#18]
Currently, we have deployed the OpenStack dashboard into container with kolla-ansible. But now with the default controller ip address without specifying any port, the dashboard cann't be connected. 

Need to find out the port used by kolla-ansible for dashboard, get the correct url format and test the logon and other operations.

**Comment by haolp** [comment]
The URL is the controller ip, like http://9.115.114.178, can login successfully.
