### ISSUE TITLE
Install kolla-ansible and dependencies automatically

### ISSUE THREAD

**Issue by dongyanyang** [mfcloud/kolla-ansible#3]
User would need a tool to automatically install the kolla-ansible and its dependencies before starting the deployment.

**Comment by jichenjc** [comment]
this should be something we guide user to do ? or create a .sh file to git clone the file and 
pip install -f requirement.txt automatically ? maybe internet is a thing to think about, create another container might be a way to do

**Comment by dongyanyang** [comment]
> this should be something we guide user to do ? or create a .sh file to git clone the file and
> pip install -f requirement.txt automatically ? maybe internet is a thing to think about, create another container might be a way to do

We need to create a script to do all the installations including repository source setups, kolla-ansible installation, dependencies packages, etc. 
Otherwise too many manual steps for users.

**Comment by dongyanyang** [comment]
Included this in the setup-deployment-server tool of this patch:
https://review.gerrithub.io/c/mfcloud/kolla-ansible/+/427052

Basic function tested.
So close this issue.
