### ISSUE TITLE
Configuration setups before using kolla-ansible to deploy x86 controller + s390x compute

### ISSUE THREAD

**Issue by dongyanyang** [mfcloud/kolla-ansible#5]
User needs a clear and convenient way to fill their own configurations before deploying x86 controller + s390x compute. eg: passwords, inventory file, globals.yml, etc.

**Comment by jichenjc** [comment]
I think we should not wrap this again, better document is the best way to go
use default as much as we can and document the to be changed as detail as we can

**Comment by dongyanyang** [comment]
> I think we should not wrap this again, better document is the best way to go
> use default as much as we can and document the to be changed as detail as we can

right. no plan to do any wrap here. Just make clear what settings we required and the acceptable values.

**Comment by dongyanyang** [comment]
1. Update setup-deployment-server to setup initial configuration sample files for user
2. Generate scripts used to setup target nodes to use local repo servers and update bootstrap-servers to run this script on target nodes at the beginning.

Code changes:
https://review.gerrithub.io/c/mfcloud/kolla-ansible/+/427299

Function tested. 

Configurations steps recorded in the following boxnote: 
 https://ibm.ent.box.com/notes/322436026997
