### ISSUE TITLE
Automate the deployment of OpenStack Queens controller on x86/ubuntu and kvm compute on LinuxONE/ubuntu

### ISSUE THREAD

**Issue by dongyanyang** [mfcloud/kolla-ansible#6]
As a user, I want to a way to deploy openstack queens controller services in container on x86/ubuntu platform and integrate LinuxONE ubuntu server as a kvm compute node conveniently and quickly even if there are multiple nodes to deploy.

**Comment by bjhuangr** [comment]
So this epic can be closed.
