### ISSUE TITLE
Automate installation and configuration of libvirtd/nova-compute/neutron-openvswitch-agent

### ISSUE THREAD

**Issue by bjhuangr** [mfcloud/kolla-ansible#9]

**Comment by jichenjc** [comment]
this is compute node plan, not the kolla ,right? so all those stuffs deploy on VM/baremetal directly?

**Comment by bjhuangr** [comment]
not for kolla. Deploy to LinuxONE LPAR kvm host.

**Comment by bjhuangr** [comment]
completed
